### ISSUE TITLE
Rendering errors

### ISSUE THREAD

**Issue by Cyberboss** [SpaceManiac/SpacemanDMM#1]
1. See ![](https://camo.githubusercontent.com/7f0c0914a941a943229b9981f923580e629c9c15/68747470733a2f2f692e696d6775722e636f6d2f704a5654544a622e706e67) vs a screenshot ![](https://user-images.githubusercontent.com/6209658/35017014-09ca2a3e-fae9-11e7-8686-eda6a73a8df9.png)

There should be a wall under the NT logo. See https://github.com/tgstation/tgstation/commits/718d9a7e1b7a7ae71d51513cebe59166280a816c

2. See ![](https://camo.githubusercontent.com/1dc76174daba111b53bcc4c7510963549f7e89c5/68747470733a2f2f692e696d6775722e636f6d2f7461716a7138432e706e67) from the spacepods PR https://github.com/tgstation/tgstation/commit/c7c51fa7a574f7f272053c20a1ce72fde3981f3c

Those SMESs by the outer shutter shouldn't be there

**Comment by SpaceManiac** [comment]
1. Needs to be fixed map-side, stacked turfs are a map bug 
![image](https://user-images.githubusercontent.com/222630/35073205-c5976372-fb9c-11e7-9fee-597ff6630344.png)
2. Is also a map issue, those SMES are there in DreamMaker
![image](https://user-images.githubusercontent.com/222630/35073557-4d21ed5c-fb9e-11e7-9bfe-a99423736357.png)

**Comment by Cyberboss** [comment]
Lol @morerobustthanyou pls
