### ISSUE TITLE
Fails to compile

### ISSUE THREAD

**Issue by dangranos** [SpaceManiac/SpacemanDMM#10]
Fails to compile with `no such file or directory` at https://github.com/SpaceManiac/SpacemanDMM/blob/master/src/qt-extras/glium_widget.rs#L134

Additonally, after adding `include()` and using `cpp_build::Config` in `build.rs`, there are multiple include errors as Qt doesn't have `.h` suffix on header files. After that, build fails with...
```
error[E0277]: the trait bound `widgets::opengl_widget::OpenGLWidget: cpp_utils::StaticCast<widgets::opengl_widget::OpenGLWidget>` is not satisfied
  --> src/qt-extras/glium_widget.rs:44:21
   |
44 |         CppBox::new(::cpp_utils::static_cast_mut(GliumWidget_new(Box::into_raw(boxed))))
   |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `cpp_utils::StaticCast<widgets::opengl_widget::OpenGLWidget>` is not implemented for `widgets::opengl_widget::OpenGLWidget`
   |
   = help: the following implementations were found:
             <widgets::opengl_widget::OpenGLWidget as cpp_utils::StaticCast<widgets::<unnamed>::paint_device::PaintDevice>>
             <widgets::opengl_widget::OpenGLWidget as cpp_utils::StaticCast<widgets::<unnamed>::object::Object>>
             <widgets::opengl_widget::OpenGLWidget as cpp_utils::StaticCast<widgets::widget::Widget>>
   = note: required because of the requirements on the impl of `cpp_utils::StaticCast<widgets::opengl_widget::OpenGLWidget>` for `glium_widget::GliumWidget`
   = note: required by `cpp_utils::static_cast_mut`
```

**Comment by SpaceManiac** [comment]
I'll look into this soon, though the editor is not really usable right now so you're not missing much.

Run `cargo build -p cli` to build the `dmm-tools` (map renderer) executable, or `cargo build -p dm-langserver` to build the language server executable.

**Comment by dangranos** [comment]
Well, I did pretty much that. Also, what can langserver do?

**Comment by SpaceManiac** [comment]
Provides [symbol lookup support](https://github.com/SpaceManiac/SpacemanDMM/tree/master/src/langserver#readme), with more to come. Currently powers this [VS Code extension](https://marketplace.visualstudio.com/items?itemName=platymuus.dm-langclient).

**Comment by dangranos** [comment]
Hmm, so it's for tab-bing? No formatting support I suspect (harhar, in an
indent based language..). Can langservers do syntax highlight?

**Comment by SpaceManiac** [comment]
I use [another extension](https://marketplace.visualstudio.com/items?itemName=gbasood.byond-dm-language-support) for syntax highlighting, it's not perfect but it's pretty good. Formatting support is ways off, but I don't think impossible.

**Comment by SpaceManiac** [comment]
Disabled the broken packages in f7b14de9e33669a57778a8b07c8181669bb16982. Kind of a hack fix but I'm not maintaining these components and they're not useful yet even if they did compile so it's better to keep things simple.
