### ISSUE TITLE
Renaming a .dm file adds #include to the .dme and doesn't remove the previous #include

### ISSUE THREAD

**Issue by Kaiochao** [SpaceManiac/SpacemanDMM#100]
If a file isn't ticked originally, it shouldn't be ticked on rename. 
Otherwise, it should replace the existing #include line.

**Comment by SpaceManiac** [comment]
Unable to reproduce. As far as I can tell the extension is correctly removing the old filename and adding the new filename to the when "Tick On Create" is enabled and doing nothing when it is disabled

**Comment by SpaceManiac** [comment]
This wasn't previously fixable, but now it is, thanks to [new APIs](https://github.com/microsoft/vscode/pull/85830) introduced in Dec 2019. The autotick functionality based on the file watcher should be replaced with using the new APIs.

**Comment by SpaceManiac** [comment]
vscode-dm-langclient v0.1.10 has been released, including a fix for this issue
