### ISSUE TITLE
Langserver crash on commenting

### ISSUE THREAD

**Issue by fizzle7** [SpaceManiac/SpacemanDMM#105]
Did a multi-line comment opening with /* and before I could close it, it crashed on the following code
```
/datum/storage_ui/default/Destroy()
	close_all()
	QDEL_NULL(boxes)	
	QDEL_NULL(storage_start)
	QDEL_NULL(storage_continue)
	QDEL_NULL(storage_end)
	QDEL_NULL(stored_start)
	QDEL_NULL(stored_continue)
	QDEL_NULL(stored_end)
	QDEL_NULL(closer)
	. = ..()
```
which I tried to comment as mentioned in the following way
```
/datum/storage_ui/default/Destroy()
	close_all()
	QDEL_NULL(boxes)	
/*
	QDEL_NULL(storage_start)
	QDEL_NULL(storage_continue)
	QDEL_NULL(storage_end)
	QDEL_NULL(stored_start)
	QDEL_NULL(stored_continue)
	QDEL_NULL(stored_end)
	QDEL_NULL(closer)
	. = ..()
```
Crash report:

> 
> dm-langserver 1.0.0  Copyright (C) 2017-2019  Tad Hardesty
> This program comes with ABSOLUTELY NO WARRANTY. This is free software,
> and you are welcome to redistribute it under the conditions of the GNU
> General Public License version 3.
> 
> executable: c:\Users\Me\.vscode\extensions\platymuus.dm-langclient-0.1.2\bin\dm-langserver-x64-win32.exe
> commit: 574f1f780eed39be19e7aeb5cd04066980458740
> build date: 2019-07-16UTC
> directory: _**OMITTED**_\Baystation12
> client capabilities: related_info: true, label_offset_support: true, object_tree: true
> workspace root: file:/// _**OMITTED**_/Baystation12/
> environment:  _**OMITTED**_\Baystation12\baystation12.dme
> parsed 23114/23114 proc bodies (100%)
> parsed in 44.132s
> "" -> None
> "sc" -> Some(Anything("sc"))
>     232 results in 0.049s
> "scr" -> Some(Anything("scr"))
>     74 results in 0.031s
> "scree" -> Some(Anything("scree"))
>     22 results in 0.035s
> "screen" -> Some(Anything("screen"))
>     22 results in 0.030s
> "screen_" -> Some(Anything("screen_"))
>     22 results in 0.029s
> "screen_loc" -> Some(Anything("screen_loc"))
>     2 results in 0.028s
> Notify NYI: $/cancelRequest => Object({"id": Number(121)})
> Notify NYI: $/cancelRequest => Object({"id": Number(733)})
> Notify NYI: $/cancelRequest => Object({"id": Number(787)})
> "" -> None
> "t" -> Some(Anything("t"))
>     2148 results in 0.077s
> Notify NYI: $/cancelRequest => Object({"id": Number(819)})
> "tras" -> Some(Anything("tras"))
>     9 results in 0.014s
> "tra" -> Some(Anything("tra"))
>     275 results in 0.036s
> "translate" -> Some(Anything("translate"))
>     8 results in 0.031s
> "" -> None
> "t" -> Some(Anything("t"))
>     2148 results in 0.074s
> Notify NYI: $/cancelRequest => Object({"id": Number(825)})
> "tra" -> Some(Anything("tra"))
>     275 results in 0.019s
> "tran" -> Some(Anything("tran"))
>     90 results in 0.038s
> "translate" -> Some(Anything("translate"))
>     8 results in 0.035s
> thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\libcore\option.rs:347:21
> stack backtrace:
>    0: <unknown>
>    1: <unknown>
>    2: <unknown>
>    3: <unknown>
>    4: <unknown>
>    5: <unknown>
>    6: <unknown>
>    7: <unknown>
>    8: <unknown>
>    9: <unknown>
>   10: <unknown>
>   11: <unknown>
>   12: <unknown>
>   13: <unknown>
>   14: <unknown>
>   15: <unknown>
>   16: <unknown>
>   17: <unknown>
> [Info  - 8:52:24 PM] Connection to server got closed. Server will restart.
> [Error - 8:52:24 PM] Request textDocument/documentSymbol failed.
> Error: Connection got disposed.
> 	at Object.dispose (C:\Users\Me\.vscode\extensions\platymuus.dm-langclient-0.1.2\dist\extension.js:1:13830)
> 	at Object.dispose (C:\Users\Me\.vscode\extensions\platymuus.dm-langclient-0.1.2\dist\extension.js:1:60029)
> 	at module.exports.t.LanguageClient.handleConnectionClosed (C:\Users\Me\.vscode\extensions\platymuus.dm-langclient-0.1.2\dist\extension.js:1:60204)
> 	at module.exports.t.LanguageClient.handleConnectionClosed (C:\Users\Me\.vscode\extensions\platymuus.dm-langclient-0.1.2\dist\extension.js:1:71472)
> 	at t (C:\Users\Me\.vscode\extensions\platymuus.dm-langclient-0.1.2\dist\extension.js:1:58405)
> 	at invoke (C:\Users\Me\.vscode\extensions\platymuus.dm-langclient-0.1.2\dist\extension.js:1:68669)
> 	at r.fire (C:\Users\Me\.vscode\extensions\platymuus.dm-langclient-0.1.2\dist\extension.js:1:69399)
> 	at U (C:\Users\Me\.vscode\extensions\platymuus.dm-langclient-0.1.2\dist\extension.js:1:6016)
> 	at invoke (C:\Users\Me\.vscode\extensions\platymuus.dm-langclient-0.1.2\dist\extension.js:1:68669)
> 	at r.fire (C:\Users\Me\.vscode\extensions\platymuus.dm-langclient-0.1.2\dist\extension.js:1:69399)
> 	at d.fireClose (C:\Users\Me\.vscode\extensions\platymuus.dm-langclient-0.1.2\dist\extension.js:1:79998)
> 	at Socket.module.exports.listen.readable.on (C:\Users\Me\.vscode\extensions\platymuus.dm-langclient-0.1.2\dist\extension.js:1:80755)
> 	at Socket.emit (events.js:187:15)
> 	at Pipe.Socket._destroy._handle.close (net.js:606:12)
> [Error - 8:52:24 PM] Request textDocument/documentSymbol failed.
> Error: Connection got disposed.
> 	at Object.dispose (C:\Users\Me\.vscode\extensions\platymuus.dm-langclient-0.1.2\dist\extension.js:1:13830)
> 	at Object.dispose (C:\Users\Me\.vscode\extensions\platymuus.dm-langclient-0.1.2\dist\extension.js:1:60029)
> 	at module.exports.t.LanguageClient.handleConnectionClosed (C:\Users\Me\.vscode\extensions\platymuus.dm-langclient-0.1.2\dist\extension.js:1:60204)
> 	at module.exports.t.LanguageClient.handleConnectionClosed (C:\Users\Me\.vscode\extensions\platymuus.dm-langclient-0.1.2\dist\extension.js:1:71472)
> 	at t (C:\Users\Me\.vscode\extensions\platymuus.dm-langclient-0.1.2\dist\extension.js:1:58405)
> 	at invoke (C:\Users\Me\.vscode\extensions\platymuus.dm-langclient-0.1.2\dist\extension.js:1:68669)
> 	at r.fire (C:\Users\Me\.vscode\extensions\platymuus.dm-langclient-0.1.2\dist\extension.js:1:69399)
> 	at U (C:\Users\Me\.vscode\extensions\platymuus.dm-langclient-0.1.2\dist\extension.js:1:6016)
> 	at invoke (C:\Users\Me\.vscode\extensions\platymuus.dm-langclient-0.1.2\dist\extension.js:1:68669)
> 	at r.fire (C:\Users\Me\.vscode\extensions\platymuus.dm-langclient-0.1.2\dist\extension.js:1:69399)
> 	at d.fireClose (C:\Users\Me\.vscode\extensions\platymuus.dm-langclient-0.1.2\dist\extension.js:1:79998)
> 	at Socket.module.exports.listen.readable.on (C:\Users\Me\.vscode\extensions\platymuus.dm-langclient-0.1.2\dist\extension.js:1:80755)
> 	at Socket.emit (events.js:187:15)
> 	at Pipe.Socket._destroy._handle.close (net.js:606:12)
> dm-langserver 1.0.0  Copyright (C) 2017-2019  Tad Hardesty
> This program comes with ABSOLUTELY NO WARRANTY. This is free software,
> and you are welcome to redistribute it under the conditions of the GNU
> General Public License version 3.
> 
> executable: c:\Users\Me\.vscode\extensions\platymuus.dm-langclient-0.1.2\bin\dm-langserver-x64-win32.exe
> commit: 574f1f780eed39be19e7aeb5cd04066980458740
> build date: 2019-07-16UTC
> directory:  _**OMITTED**_\Baystation12
> client capabilities: related_info: true, label_offset_support: true, object_tree: true
> workspace root: file:/// _**OMITTED**_/Baystation12/
> environment:  _**OMITTED**_\Baystation12\baystation12.dme
> parsed 23114/23114 proc bodies (100%)
> parsed in 10.515s
> Notify NYI: $/cancelRequest => Object({"id": Number(2)})
> Notify NYI: $/cancelRequest => Object({"id": Number(3)})
> Notify NYI: $/cancelRequest => Object({"id": Number(1)})
> Notify NYI: $/cancelRequest => Object({"id": Number(4)})
> Notify NYI: $/cancelRequest => Object({"id": Number(5)})
> Notify NYI: $/cancelRequest => Object({"id": Number(6)})
> Notify NYI: $/cancelRequest => Object({"id": Number(7)})
>

**Comment by SpaceManiac** [comment]
Fixed as of f24e8d25a2fc1d212f682731b8492ef2dee908d9.
