### ISSUE TITLE
dreamchecker settings don't read TRUE macro as input

### ISSUE THREAD

**Issue by willox** [SpaceManiac/SpacemanDMM#106]
I noticed that the following code will not error:

```
/datum/proc/Method()
	set SpacemanDMM_should_call_parent = TRUE
	return 1

/datum/test/Method()
	return 2
```

While this will:
```
/datum/proc/Method()
	set SpacemanDMM_should_call_parent = 1
	return 1

/datum/test/Method()
	return 2
```

I changed the builtins code to re-add TRUE and FALSE to the builtin macros (rather than consts, the opposite of https://github.com/SpaceManiac/SpacemanDMM/commit/5da1cbff78703529b8ffa7cbc2d756f62ecfe76c) and managed to fix this behaviour locally, but I'm not sure what the correct fix would be.

**Comment by SpaceManiac** [comment]
The best fix for now is what you suggest, re-adding TRUE and FALSE as built-in macros in SpacemanDMM's view, even if this is not entirely true to life.

A more reasoned fix would require the setting to be constant-evaluated rather than merely checked whether it's literally `1` or not
