### ISSUE TITLE
Issues with finding consts defined in files included in files

### ISSUE THREAD

**Issue by comma** [SpaceManiac/SpacemanDMM#110]
On bay we have .dm files for maps that hold #include instructions for all files needed for that map.
But in some files langserv is throwing errors like this:
`unknown variable: access_expedition_shuttle`
erroring file is `maps\torch\torch_areas.dm` (and couple more in same folder), 
`access_expedition_shuttle` is a const defined in 
`maps\torch\job\torch_access.dm`

Both files are included in `maps\torch\torch.dm`. Tried changing order they're included on, didn't do a thing.

Can get code here https://github.com/Baystation12/Baystation12

**Comment by SpaceManiac** [comment]
"unknown variable" errors are caused due to this parsing failure described in #109:

```
maps/torch/torch_shuttles.dm, line 40, column 1:
error: got '6', expected one of: '/', '[', contents, newline, identifier
- fatal error: the parser cannot continue
```

I consider it a diagnostics bug that the fatal parser error does not suppress these "unknown variable" errors.
