### ISSUE TITLE
Doesn't handle modularized code properly

### ISSUE THREAD

**Issue by MCterra10** [SpaceManiac/SpacemanDMM#111]
Basically, we have an includes.dm file in our modularized code folder which uses relative pathing and the same directory structure as the main /tg/ codebase, and as such includes in that file set off the duplicate include warning and fail CI even though they are actually distinct files.
Appending the location of the file specifying the includes to the start of the checked path would probably suffice to fix this

**Comment by SpaceManiac** [comment]
Resolving a `#include` string to a file path currently searches relative to the `.dme` before searching relative to the file in which the `#include` appears, which may be wrong. I'll have to test further.

**Comment by SpaceManiac** [comment]
Committed a fix for this.

If you want a workaround for CI with the suite 1.1 binaries, you can `cd` to any dummy directory and use `dreamchecker -e path/to/austation.dme` and the `#include` resolution will do the right thing.
