### ISSUE TITLE
BYOND 513 support

### ISSUE THREAD

**Issue by Archemagus** [SpaceManiac/SpacemanDMM#112]
In 513.1493 Lummox added new text procs to BYOND. But SpacemanDMM didn't response them.

It wouldn 't be bad if sometime they join Language Server too.
![image](https://user-images.githubusercontent.com/32466328/68543872-e433cb00-03cd-11ea-8633-cb4ddcbf8e2e.png)
![image](https://user-images.githubusercontent.com/32466328/68543882-fc0b4f00-03cd-11ea-832b-9b5c3df3d83b.png)
And later splittext_char()
![image](https://user-images.githubusercontent.com/32466328/68543892-19d8b400-03ce-11ea-86ac-3d0eae9d5700.png)
http://www.byond.com/docs/notes/513.html

**Comment by SpaceManiac** [comment]
For now, SpacemanDMM implements BYOND 512. Gating use of new functions behind directives like `#if DM_VERSION >= 513` will appease dreamchecker, with the added benefit that your project will still compile on 512.
