### ISSUE TITLE
Mixed indentation causing incorrect linter error

### ISSUE THREAD

**Issue by spookydonut** [SpaceManiac/SpacemanDMM#117]
![image](https://user-images.githubusercontent.com/765153/69917796-e6f17f80-14a4-11ea-9e69-c4a9a5900c48.png)
```
code/modules/orbits/spaceship.dm, line 192, column 102:
error: got '{', expected one of: operator, field access, as, 'in', ',', ';'
```
obviously theres no `{` and the actual error is the space at the start of the new line, weirdly DM compiles this.
Line endings are LF

**Comment by SpaceManiac** [comment]
The indentation processor turns the indented line into a `{}` block and then the later parser stage sees a `{` where something else should be.

Maybe the error message could be improved, but it is a real mistake.

**Comment by spookydonut** [comment]
Found a new instance of this
```
var/i = 0
	for(;;)
		i++
```
