### ISSUE TITLE
gotos are undefined vars 

### ISSUE THREAD

**Issue by ZeWaka** [SpaceManiac/SpacemanDMM#135]
Issue: 'error: undefined var: "baz"' on parsing a goto baz

Example:
```
foo()
  if(bloop)
    goto baz
  stuff

  baz
  stuff
  return
```

**Comment by SpaceManiac** [comment]
I don't agree with idents on a line by themselves counting as labels, add a `:` to distinguish it syntactically

**Comment by spookydonut** [comment]
goto <expression::term::ident> could add <expression::term::ident> to a list of labels in that proc body, and be a configurable waarning

**Comment by SpaceManiac** [comment]
WONTFIXing this. Rules like "if an expression statement consists of a single identifier, it is instead a label" are nonsense. Add the colon.
