### ISSUE TITLE
Rendering In Multiple Z Levels

### ISSUE THREAD

**Issue by TheFurryFeline** [SpaceManiac/SpacemanDMM#141]
Hello, I'm here to ask about whether there is a way to ascertain for map files with multiple z-levels can have their difference renders found other than merely the first of the list. For instance, one map file has a height of 3 decks. You Change something for two or all three levels. MapDiffBot runs and I can only ever see the bottom layer's difference in the renders.

Once more, is there a way to view multiple levels' renders for a single map file?

**Comment by SpaceManiac** [comment]
SpacemanDMM's rendering engine supports multi-Z map files. I haven't checked, but if as you say MapDiffBot doesn't support them, the issue is on that side: https://github.com/tgstation/MapDiffBot/issues

**Comment by TheFurryFeline** [comment]
My question was just how I go about finding if it's already in or not and seeing each level of difference renders for a map file.

**Comment by SpaceManiac** [comment]
Running a render with SpacemanDMM will render all z-levels of the map by default.

**Comment by TheFurryFeline** [comment]
The codebases I work with use MapDiffBot. Sorry for posting my question in the wrong repo! Thanks for your time.
