### ISSUE TITLE
Polaris has not received free code cleanup yet

### ISSUE THREAD

**Issue by lbnesquik** [SpaceManiac/SpacemanDMM#151]
This extension keeps bringing up errors in many different files which i know aren't actually issues given it compiles. It would be great to have an option to disable error/syntax callouts. I am not sure what terms to even use to make this issue, but that would be great.

![image](https://user-images.githubusercontent.com/24830358/72434585-43320980-379c-11ea-8fc2-6b946bc60ba6.png)

![image](https://user-images.githubusercontent.com/24830358/72434849-ef73f000-379c-11ea-9c09-4e5d84e5c6e3.png)

**Comment by SpaceManiac** [comment]
There are three main classes of diagnostics emitted by the extension:

1. Fatal errors which prevent the extension from doing its job. In some cases, BYOND will successfully compile code that the extension is not equipped to understand. Some instances are too onerous to fix, but bug reports with specifics are welcome.

2. Warnings which indicate obvious syntax problems in your code and make the extension's job more difficult but not impossible, or which are very likely to be programmer mistakes. Some warnings of this type are now possible to disable with a [configuration file](https://github.com/SpaceManiac/SpacemanDMM/blob/master/CONFIGURING.md). Diagnostics which can be disabled will have `dm-langserver(<error_type_name>)` written next to them in the Problems pane.

3. Warnings which are generated by the [dreamchecker](https://github.com/SpaceManiac/SpacemanDMM/tree/master/src/dreamchecker) component. This component is disabled by default. It does a deeper semantic analysis of your code looking for areas likely to cause runtime errors.

Most likely the diagnostics you are seeing are in category 2. I can provide more specific help if you say what errors you are seeing specifically.

**Comment by lbnesquik** [comment]
Looking more closely, it seems only Polaris and polaris downstreams have this issue.

**Comment by SpaceManiac** [comment]
Looks like Polaris was overlooked when I was going around fixing everybody's codebases. I might get to it at some point or I might not. Some of the errors are type 1 but most are type 2.

**Comment by lbnesquik** [comment]
@SpaceManiac Wow, thank you for all of this work, dude, you rock!
