### ISSUE TITLE
undefined field: "opacity" on /mutable_appearance

### ISSUE THREAD

**Issue by ZeWaka** [SpaceManiac/SpacemanDMM#178]
[DREAMCHECKER]
This is indeed a variable for mutable_appearance according to the BYOND docs: http://www.byond.com/docs/ref/#/mutable_appearance/var

Code that uses this:
https://github.com/goonstation/goonstation/blob/01afa9f9ea5a1b68cdae748fee422ebb3dd8b107/code/modules/fluids/fluid_groups.dm#L572

**Comment by spookydonut** [comment]
Fixed by https://github.com/SpaceManiac/SpacemanDMM/commit/d79db98b0681c8760667103f98e268c3347b5187
