### ISSUE TITLE
Blank images generated from diff bot

### ISSUE THREAD

**Issue by Razgriz1032** [SpaceManiac/SpacemanDMM#182]
Diff bot is generating blank .png's for all map pull requests.

Here is an example link to a PR
https://github.com/CHOMPStation2/CHOMPStation2/pull/324/checks?check_run_id=654484981

And here's the images generated.
https://mdb.affectedarc07.co.uk/Files/228495881/654484981/0/before.png
https://mdb.affectedarc07.co.uk/Files/228495881/654484981/0/after.png
https://mdb.affectedarc07.co.uk/Files/228495881/654484981/0/diff.png

**Comment by Razgriz1032** [comment]
Wasn't sure if this goes in diff bot repo or if this goes here because it seems like a rendering issue?
Link to same issue on other repo:
https://github.com/tgstation/MapDiffBot/issues/116

**Comment by Razgriz1032** [comment]
Actually, found the log. I am seeing a lot of "bad path."

These all used to say "bad icon" and it would run fine, so I'm thinking that is of significance somehow and I don't know what it means.
https://mdb.affectedarc07.co.uk/Files/228495881/654484981/0/logs.txt

**Comment by SpaceManiac** [comment]
I was able to successfully render the map in that PR using SpacemanDMM, so this seems to be a MapDiffBot issue.

"bad icon" is coming from applying /tg/ prettifiers to a non-/tg/ codebase, and can generally be safely ignored.

**Comment by Razgriz1032** [comment]
Got it, thanks. I'll close this issue.
