### ISSUE TITLE
/mutable_appearance should have more vars than /image + opacity

### ISSUE THREAD

**Issue by Kaiochao** [SpaceManiac/SpacemanDMM#186]
https://github.com/SpaceManiac/SpacemanDMM/blob/35915f7cb9dc65c8450e43352eb5a2676f97d37f/src/dreammaker/builtins.rs#L941-L942

**Comment by SpaceManiac** [comment]
like what

**Comment by Kaiochao** [comment]
Well, just from difference in what the docs show for `vars (mutable_appearance)` and `vars (image)`:

**/mutable_appearance vars that /image isn't documented to have:** 

- density
- desc
- gender
- invisibility
- layer
- luminosity
- animate_movement
- mouse_over_pointer
- mouse_drag_pointer
- mouse_drop_pointer
- mouse_drop_zone
- mouse_opacity
- name
- opacity
- screen_loc
- suffix
- verbs
- vis_flags

**/image vars that /mutable_appearance isn't documented to have:** 

- loc
- override
- render_source
- render_target
- vis_contents
- x
- y
- z
- type
- tag
- parent_type

**Comment by SpaceManiac** [comment]
The docs have this to say:

> The /mutable_appearance datum is technically a descendant of /image, but this is only for convenience, and should not be relied on for any other purpose as it is subject to change in future versions. 

I have to strike a balance between implementing DM as documented and implementing DM as actually used. In this case I am making available the same set of vars on `/image` and on `/mutable_appearance` that the DM compiler does.
