### ISSUE TITLE
"call to pure proc discards return value" when it doesn't

### ISSUE THREAD

**Issue by Kaiochao** [SpaceManiac/SpacemanDMM#188]
```dm
// Thing() is pure and not really being discarded. 
Thing().DoStuff()
```
Also, `DoStuff` isn't parsed as a reference (can't jump to definition). Another issue?

**Comment by SpaceManiac** [comment]
> Also, DoStuff isn't parsed as a reference (can't jump to definition). Another issue?
Split to #200.
