### ISSUE TITLE
Suggestion: Bay-based fancy rendering

### ISSUE THREAD

**Issue by AffectedArc07** [SpaceManiac/SpacemanDMM#19]
Request/Suggestion:

Currently when rending maps based off baycode, it just generates the in-editor version, which means non-transparent space, markers showing, cables showing, consoles off, etc.

Any way this can be fixed?

**Comment by SpaceManiac** [comment]
I already hardcode /tg/ fancy rendering and would like to avoid hardcoding a second set (especially from a codebase I'm unfamiliar with). It ought to be made configurable somehow, but I haven't settled on a form that would take.

**Comment by AffectedArc07** [comment]
Maybe a config for things to hide?

**Comment by AffectedArc07** [comment]
@SpaceManiac how does the current fancy-rendering system?

**Comment by SpaceManiac** [comment]
Basically for every atom with fancy rendering, I hardcoded the typepaths and var names and translated the logic from DM to Rust. Everything is in the `src/tools/render_passes/` directory. I really need to figure out some better way to express it.

**Comment by AffectedArc07** [comment]
Maybe have some form of JSON with pathtypes to hide, icons to replace, etc, then add a render option of `-config file.json`

**Comment by AffectedArc07** [comment]
I made this work with the power of shitcode
