### ISSUE TITLE
Go to Definition should work for relative-pathed proc parameter types not preceded by var/

### ISSUE THREAD

**Issue by Kaiochao** [SpaceManiac/SpacemanDMM#190]
```dm
thing
	proc/a(thing/blah)
	proc
		b(thing/blah)
		c(var/thing/blah) // works
proc/a(thing/blah) // works
proc
	b(thing/blah)
```

**Comment by SpaceManiac** [comment]
I cannot seem to reproduce the bug. Can you post a code snippet, including a use of the identifier that cannot be ctrl+clicked but should be, even after a reparse (Ctrl+Shift+B)?

**Comment by Kaiochao** [comment]
The snippet in the original post includes 3 occurrences of `thing` that can't be ctrl+clicked, on every line that doesn't have `// works` afterwards.

**Comment by SpaceManiac** [comment]
Thanks for clarifying, I'll investigate further
