### ISSUE TITLE
Syntax highlighting wishlist

### ISSUE THREAD

**Issue by SpaceManiac** [SpaceManiac/SpacemanDMM#191]
Syntax highlighting is currently provided by [vscode-atomic-dreams](https://github.com/gbasood/vscode-atomic-dreams/), but it may be desirable to bring it in-tree with vscode-dm-langclient to accomplish some improvements:

* [x] Code parts of interpolated strings should be highlighted more like code than like strings
  * [x] Also, in `"[FOO + BAR[1] + BAZ]"`, the interpolation region ends at the first `]` instead of the second
* [x] Backslashes at the end of a `//` comment line should extend the comment highlighting to the next line
* [x] Raw strings like <code>@@[aeiouAEIOU "'()[\]{}.!?,:;_`~-]@</code>
* [x] Raw strings like `var/blah = @(#whatever#)blah#whatever#`
* [x] Missing `try`, `catch`, and `throw` keywords
* [x] Missing `\t`, `\x`, `\u`, `\U` escapes

~~Related, but probably a separate project:~~
* ~~It may be possible to use the language server to power semantic highlighting (macros, locals, fields, types, keywords, etc.)~~
* Moved to #337.

**Comment by Cyberboss** [comment]
Feelin' cute, might do this.

**Comment by Cyberboss** [comment]
Happening in langserver 3.16 which is being drafted

**Comment by ZeWaka** [comment]
3.16 is complete: https://microsoft.github.io/language-server-protocol/specifications/specification-current/

**Comment by JJRcop** [comment]
What kind of work would be required for this, would it involve adapting [vscode-atomic-dreams] to dm-langserver?

[vscode-atomic-dreams]: https://github.com/gbasood/vscode-atomic-dreams/

**Comment by SpaceManiac** [comment]
The first four items listed in the OP consist essentially of integrating vscode-atomic-dreams into [vscode-dm-langclient](https://github.com/SpaceManiac/vscode-dm-langclient) so that it becomes a one-stop-shop, then updating it.

The langserver integration is a separate step with the purpose of replacing rules like "highlight anything in all-caps like a macro" with highlighting based on whether something *actually is* a macro.

**Comment by SpaceManiac** [comment]
vscode-dm-langclient v0.2.0 now bundles a much-improved DM syntax highlighting definition, superseding vscode-atomic-dreams

**Comment by JJRcop** [comment]
Can this be brought out of [vscode-dm-langclient](https://github.com/SpaceManiac/vscode-dm-langclient) and into dm-langclient? It would be great to see DM syntax highlighting outside of VS code, and now it's supported, like @ZeWaka mentioned earlier:

> 3.16 is complete: https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_semanticTokens

Maybe that's the entire point of this issue, and I misunderstood.

**Comment by JJRcop** [comment]
I am slightly confused if the dm-langserver integration step is planned or not. Looking forward to it since I don't use VS code, but do use an editor which supports LSP, and would love DM-specific syntax highlighting.

**Comment by SpaceManiac** [comment]
> I am slightly confused if the dm-langserver integration step is planned or not. Looking forward to it since I don't use VS code, but do use an editor which supports LSP, and would love DM-specific syntax highlighting.

It's a possible future feature, but I don't currently plan to work on it any time soon. You'll probably get better mileage by porting the old-school syntax definitions to your editor of choice.
