### ISSUE TITLE
bad precedence for bit ops

### ISSUE THREAD

**Issue by mloc** [SpaceManiac/SpacemanDMM#196]
In DM, `1 | 6 & 2` is parsed as `1 | (6 & 2)` and returns 3.
Instead, we parse it as `(1 | 6) & 2`, as all bit ops are treated as having the same precedence.
According to ref, precedence should be `&` > `^` > `|`

**Comment by SpaceManiac** [comment]
This should be a matter of updating the binary op precedence table in the parser
