### ISSUE TITLE
Rendering certain maps with --disable hide-space results in no output

### ISSUE THREAD

**Issue by Cyberboss** [SpaceManiac/SpacemanDMM#2]
e.g. Boxstation and Deltastation in https://github.com/tgstation/tgstation/commit/a239c63c20828bf1520bd0b872e48e652818ef15

**Comment by SpaceManiac** [comment]
Trolled by the argument parser, I'll see if I can fix this somehow. As a workaround, either write `deltastation.dmm --disable hide-space` or `--disable hide-space -- deltastation.dmm`.
