### ISSUE TITLE
SHOULD_NOT_SLEEP does not check overrides of procs being called for sleeps

### ISSUE THREAD

**Issue by silicons** [SpaceManiac/SpacemanDMM#203]
> please make winget considered a sleep for SHOULD_NOT_SLEEP

i have lost too much sleep hunting down a sleep() until i realized it was a winset after weeks of debugging please make it considered a sleep for SHOULD_NOT_SLEEP because AAAAAAAAAAAAAA

**Comment by Cyberboss** [comment]
Seems like it already should https://github.com/SpaceManiac/SpacemanDMM/blob/ac037752c930030a46f4ddcb7e39b199246d19d1/src/dreamchecker/lib.rs#L1605

**Comment by spookydonut** [comment]
@silicons @Cyberboss winget is blocking, winset is not

**Comment by Cyberboss** [comment]
Blocking or sleeping? I thought we all agreed it slept

**Comment by Cyberboss** [comment]
Also @silicons meant to say winget in OP

**Comment by SpaceManiac** [comment]
> it's forcesay() on tgcode i believe, unless someone already added waitfor = FALSE
> i had put SHOULD_NOT_SLEEP on ClickOn() and it didn't detect it
> ClickOn() --> melee_attack_chain --> attackby --> attack --> baton_stun --> forcesay

The actual issue is that the check, when seeing a call to `x.attack()` on an `/obj/item` variable, only looks to see whether `/obj/item/proc/attack()` sleeps and not whether any of its overrides such as `/obj/item/stunbaton/attack()` sleep.
