### ISSUE TITLE
"naked" sleep doesn't parse

### ISSUE THREAD

**Issue by mloc** [SpaceManiac/SpacemanDMM#207]
`sleep 1` is a valid DM statement, but it doesn't parse.
`sleep` is treated as a builtin proc, but it's more akin to `spawn`.

**Comment by SpaceManiac** [comment]
I will note that this is not documented http://www.byond.com/docs/ref/info.html#/proc/sleep

**Comment by SpaceManiac** [comment]
I am wontfixing this for now.
