### ISSUE TITLE
"<file name>.dmi" File not found if you modify it and try to compile

### ISSUE THREAD

**Issue by Dominig12** [SpaceManiac/SpacemanDMM#209]
If you change the file and save, when compiling in VsCode, it gives an error that it cannot find the file, to fix this you need to compile in Dream Maker, and then start compilation in VsCode again

**Comment by SpaceManiac** [comment]
Not fixable. Dream Daemon holds a lock on the .rsc file while a server is running and Dream Maker holds a lock on the .rsc file while it's being used for mapping, which prevent the command-line dm.exe from modifying it. Note that the "file not found" message is preceded by a "BUG: x.rsc is locked!" line.

**Comment by Dominig12** [comment]
I see, thank you for the information
