### ISSUE TITLE
The colon access operator doesn't parse

### ISSUE THREAD

**Issue by SpaceManiac** [SpaceManiac/SpacemanDMM#21]
The biggest cause of proc parse failures due to `is_type_in_typecache` using the `:` operator. The big problem is that `a : b` and `a:b` are different and need to be treated differently.

Prefabs need to accept nonspaced path operators only:
* `thing ? /obj : /mob` is `(thing) ? (/obj) : (/mob)`

Field accesses need to accept nonspaced operators only:
* `thing ? a : b():c` is `(thing) ? (a) : (b():c)`
* `thing ? a:b() : c` is `(thing) ? (a:b()) : (c)`

But note that:
* `thing?1:2` is valid
* `thing?a:b` is not

**Comment by Cyberboss** [comment]
fucking byond lol

**Comment by SpaceManiac** [comment]
Completed, if messily, in 990e61050c616ff61d1fdf7475c6d5f499bc8aab
