### ISSUE TITLE
Feature Request: DMDoc comment type after member

### ISSUE THREAD

**Issue by ZeWaka** [SpaceManiac/SpacemanDMM#221]
Implementing inline-comment type of doxygen format seen here:
https://www.doxygen.nl/manual/docblocks.html#memberdoc

I think only `///< foo` would be necessary, but for Qt-style, `/**< foo */` could be implemented as well

Could also be implemented as `//<` for terseness.

DM code example:
```dm
/obj/foo
  var/bar ///< This is a doc comment for 'bar'.
```

**Comment by SpaceManiac** [comment]
`//!` is supposed to be this but it's broken

**Comment by SpaceManiac** [comment]
Fixed along with https://github.com/SpaceManiac/SpacemanDMM/issues/332
