### ISSUE TITLE
Feature Request: DMDoc auto complete

### ISSUE THREAD

**Issue by Cyberboss** [SpaceManiac/SpacemanDMM#225]
In VS C#, when you type `///` above a function or method, the multiline syntax for doc comments is generated for you. It would be nice if we could get the same in DM for procs with arguments

i.e.
```dm
/proc/foo(obj/bar, datum/baz/barf)
    ...
```

Typing:
```dm
///
/proc/foo(obj/bar, datum/baz/barf)
    ...
```

Should generate:
```dm
/**
  * |
  *
  * * bar -
  * * barf -
  */
/proc/foo(obj/bar, datum/baz/barf)
    ...
```

`|` being the new cursor position

**Comment by Cyberboss** [comment]
Note similar functionality in the Auto Doc Comment extension shown in this PR https://github.com/tgstation/tgstation/pull/54623.

While not exactly what I requested, I'd understand if this wasn't something to add because that exists

**Comment by ZeWaka** [comment]
done here: https://marketplace.visualstudio.com/items?itemName=stylemistake.auto-comment-blocks

**Comment by Cyberboss** [comment]
Closing this then
