### ISSUE TITLE
Dreamchecker complains that /proc is an undefined type, when it's not, really

### ISSUE THREAD

**Issue by Amunak** [SpaceManiac/SpacemanDMM#227]
Consider this chunk of code that detects a type of variable ([context](https://github.com/Aurorastation/Aurora.3/pull/10442/files#diff-c449e7b190a41d494d9e36e6ec7fdce6e577c3e13119137566559de753ab35d9R1059-R1063)):
```dm
/proc/get_proc_type(var/V)
	var/proc/P = V
	if(P) // it's a proc of some kind
		if(istext(P?:name) && P:name != "") // procs with names are generally verbs
			return "verb"
		return "proc"
	return "something else"
```

Dreamchecker would [complain](https://travis-ci.com/github/Aurorastation/Aurora.3/jobs/427066863#L861-L862) with "error: undefined type: /proc" that it's not a valid type, but it absolutely is when you pass it, say, the verbs from `mob.verb`:

![dreamseeker_2020-11-03_18-51-11](https://user-images.githubusercontent.com/781546/98023122-c47b8b00-1e06-11eb-98a3-657ce38841a7.png)

**Comment by SpaceManiac** [comment]
The `proc` keyword in the typepath is being silently ignored by the compiler. This is evident in the fact that you need `:` syntax to access its fields. I chose to have SpacemanDMM complain about this instead. /tg/ uses a fake type to make the variables accessible via `.` syntax: https://codedocs.tgstation13.org/procpath.html

Your `if(P)` check is not doing what you think it is; it's only checking that `V` is truthy, not that it is a proc or verb path.

**Comment by Amunak** [comment]
Thanks, that makes sense. With some ideas from #coderbus I made the check abainst the Byond types from the objects' refs.
