### ISSUE TITLE
`proc` relpath blocks in a codebase cause cascading errors

### ISSUE THREAD

**Issue by Crazylemon64** [SpaceManiac/SpacemanDMM#23]
To reproduce:

```
/datum/dummy
    proc
        hello()
```

In contemporary SS13 codebases, this can be found to cause many "nested absolute path" warnings and several "proc looks like a var" errors. (Tested on both paracode and tgstation)

This appears to have been introduced within the past 24 hours of commits.

**Comment by SpaceManiac** [comment]
I was able to reproduce by downloading Paradise. Should be fixed in f580071c5e9d5030081d2bae994cc096e727cf8c.
