### ISSUE TITLE
Sublime Text language client package broken due to get_initialize_params change

### ISSUE THREAD

**Issue by KubeRoot** [SpaceManiac/SpacemanDMM#231]
The language client errors while starting up, with the following error

> Could not start dm-langserver
> get_initialize_params() takes 2 positional arguments but 3 were given
> Server will be disabled for this window

The error seems to be caused by this commit in SublimeLSP: https://github.com/sublimelsp/LSP/commit/e65fe3ce3fcf0ed89f640f944a9076225f3f9795, which changes the signature of `get_initialize_params` signature from

```py
def get_initialize_params(workspace_folders: List[WorkspaceFolder], config: ClientConfig) -> dict
```

to

```py
def get_initialize_params(variables: Dict[str, str], workspace_folders: List[WorkspaceFolder],
                          config: ClientConfig) -> dict
```

Specifically, the language client package replaces `get_initialize_params` with a modified version with the old signature.

**Comment by SpaceManiac** [comment]
[A fix](https://github.com/SpaceManiac/sublime-dm-langclient/commit/c8bb2f187e5472fc140da4b033dbc0a68ac0ec37) has been published. It may be a bit before Package Control picks up on the new version.

**Comment by KubeRoot** [comment]
Latest version on Package Control is working now, thanks for the quick fix!
