### ISSUE TITLE
[Feature Request] Add options for dmm-tools as part of SpacemanDMM.toml

### ISSUE THREAD

**Issue by AffectedArc07** [SpaceManiac/SpacemanDMM#237]
**What:**
Requesting that a config section in `SpacemanDMM.toml` be added for `dmm-tools`, which can enable and disable render passes by config. Command line parameters will still take precedence. 

**Why:**
Would be a massive help for MapDiffBot among other things, as this would provide a clean and safe way of users enabling and disabling render passes to suit their codebases. Any codebase which is currently not using smart cables (good choice) currently cannot get any wire renderings out of MapDiffBot at all, and I would rather not pass raw user input to a command line.

**Comment by SpaceManiac** [comment]
This was added in a19cc58e32905d7ba9b7f24aecadc751b2fdb0d5.
