### ISSUE TITLE
`for()` syntax marked as error

### ISSUE THREAD

**Issue by warriorstar-orion** [SpaceManiac/SpacemanDMM#249]
Hello, thanks for all your work;

I have the following DME: https://gist.github.com/warriorstar-orion/dc6091aa63d43742fe502c9eef8716eb

I maintain a branch of SpacemanDMM which, upon parsing an AST, serializes it to Protobuf (https://github.com/SpaceManiac/SpacemanDMM/compare/master...warriorstar-orion:pb2 to compare against master). Upon parsing the above DME and ingesting the protobuf in another program, I found that the parser doesn't appear to respect the `for` syntax with no arguments:

```
2021/02/25 12:55:21   0.00s parsing
2021/02/25 12:55:21 ===================
Invalid code block found:
invalid: true
invalid_description: "for-in-list must start with variable"


2021/02/25 12:55:21 ===================
Invalid code block found:
invalid: true
invalid_description: "for-in-list must start with variable"
```

Based on a read of the Designer's Guide and DM Reference, it appears this syntax is valid. The Designer's Guide uses a roughly equivalent example:

<img width="718" alt="Screen Shot 2021-02-25 at 13 06 24" src="https://user-images.githubusercontent.com/59303604/109196938-5c143900-776a-11eb-940c-b70ab67a8dc2.png">

And the DM Reference suggests all three loop arguments may be omitted:

<img width="885" alt="Screen Shot 2021-02-25 at 13 06 45" src="https://user-images.githubusercontent.com/59303604/109196960-63d3dd80-776a-11eb-9382-90af742c945d.png">

Am I holding it wrong or is parsing support for this missing here?

Thanks!

EDIT: I'll probably just switch to e.g. `while(1)` but leave this for posterity

**Comment by ZeWaka** [comment]
Yeah, this is used nowhere in SS13 and you'd probably be shamed if you did use it.
