### ISSUE TITLE
Macros in DMM files - cannot reference variables in this context

### ISSUE THREAD

**Issue by Sovexe** [SpaceManiac/SpacemanDMM#251]
Originally reported on MapDiffBot https://github.com/tgstation/MapDiffBot/issues/129 however I've been informed that this is a SpacemanDMM issue

--

SpacemanDMM doesn't appear to support macros in dmm files

example from goonstation z2.dmm of in an in map macro

```dm
"dkP" = (
/obj/landmark/escape_pod_succ{
	shuttle = SHUTTLE_SOUTH
	},
/turf/space/shuttle_transit,
/area/shuttle_transit_space/north)
```
example of error output from a MapDiffBot log, see `cannot reference variables in this context error `
https://mdb.affectedarc07.co.uk/Files/252047483/2013182595/0/logs.txt

this appears to be a known issue already as per a reference in https://github.com/SpaceManiac/SpacemanDMM/issues/13

**Comment by SpaceManiac** [comment]
SpacemanDMM doesn't support this because Dream Maker doesn't support this (and neither does /tg/station's map loader). Your map is invalid. You should replace `SHUTTLE_SOUTH` with whatever the actual value is.
