### ISSUE TITLE
Follow recommended Rust package structure

### ISSUE THREAD

**Issue by Kylebrown9** [SpaceManiac/SpacemanDMM#287]
The source code in the language server directory is not organized in the recommended way.
https://doc.rust-lang.org/cargo/guide/project-layout.html

This makes it more difficult for Rust programmers to read and navigate the code base, than if it did follow them.

**Comment by PJB3005** [comment]
What's the problem with the current structure? The fact that the `Cargo.toml` is next to the `.rs` files directly in the projects?

**Comment by Kylebrown9** [comment]
For the purpose of this analysis, I'm going to interpret your project as having a root crate at the repository root and a number of smaller interdependent crates that serve specific functionalities. This in itself is completely normal for a Rust project. My suggestion is to make the root crate and each of the smaller crates follow the guidelines on the above page (and additionally follow the conventions on locating sub-crates).

### `Cargo.toml`s
In the current folder structure, the location of each of the `Cargo.toml` files is correct.
They are in the root of their respective crates.

### Crate `src/` Folders
Following these guidelines, there would be an `src` directory in each of the crates and all source code would go there.
> Source code goes in the `src` directory.

This is what I had meant to comment on specifically, but I realize my comment was unclear.
(Note that build.rs is an exception, it belongs in the crate root so cargo knows to run it as such.)

### Location of the Sub-Crates
Placing the sub-crates in the `src/` folder would tend to violate my expectations.
Usually these are either placed in a dedicated non-`src/` folder or in the project root.
The `src/` folder is expected to be a singular module tree for the containing crate.

I've searched for "popular rust packages" and added the ones with sub-crates to the examples below.

* [`bevy`](https://github.com/bevyengine/bevy) - All sub-crates located in dedicated [`crates`](https://github.com/bevyengine/bevy/tree/main/crates) folder
* [`nom`](https://github.com/Geal/nom) - Sub-crate [`fuzz`](https://github.com/Geal/nom/tree/master/fuzz) is located in project root
* [`rocket`](https://github.com/SergioBenitez/Rocket) - Has sub-crates in a few dedicated folders: [`core`](https://github.com/SergioBenitez/Rocket/tree/master/core), [`contrib`](https://github.com/SergioBenitez/Rocket/tree/master/contrib), and in the root [`benchmarks`](https://github.com/SergioBenitez/Rocket/tree/master/benchmarks)
* [`tokio`](https://github.com/tokio-rs/tokio) - Has sub-crates in the project root e.g. [`tokio-macros`](https://github.com/tokio-rs/tokio/tree/master/tokio-macros)
* [`serde`](https://github.com/serde-rs/serde) - Has sub-crates in the project root e.g. [`serde-derive`](https://github.com/serde-rs/serde/tree/master/serde_derive)

**Comment by SpaceManiac** [comment]
Fixed. I saw fit to follow bevy's example with a `crates` directory.
