### ISSUE TITLE
Cannot use .dme other than tg's if they are in the same directory

### ISSUE THREAD

**Issue by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [SpaceManiac/SpacemanDMM#29]
Case in point: Yogs. Open the project folder and weep as you are bombarded with errors.

**Comment by Cyberboss** [comment]
Pretty sure there's a command line option that overrides a specific .dme

It's in MapDiffBot in Generator.cs somewhere

**Comment by SpaceManiac** [comment]
As of 9b0c9c8b6375143c0df6230c68eef7d8c7fbba21, the language server follows the same logic in environment detection as everything else, where it skips `tgstation.dme` if another `.dme` file is available. The fix has been deployed.

If someone manages to need two `.dme`s in the same folder and one of them isn't `tgstation.dme` for mirroring reasons they should reconsider their strategy. Or open another issue requesting a config of some sort.
