### ISSUE TITLE
VS Code extension is unable to download dm-langserver binary

### ISSUE THREAD

**Issue by douglasparker** [SpaceManiac/SpacemanDMM#299]
There seems to be an expired SSL certificate that is preventing the dm-langserver extension from downloading the appropriate binary.

![image](https://user-images.githubusercontent.com/18235822/143081189-8cfbdf8e-e4f1-451a-bb18-a91363081728.png)

**Comment by SpaceManiac** [comment]
See #298 for cause and workaround
