### ISSUE TITLE
Editor: DM errors should be reported instead of silently ignored

### ISSUE THREAD

**Issue by DamianX** [SpaceManiac/SpacemanDMM#32]
Running SpacemanDMM 9b0c9c8b6375143c0df6230c68eef7d8c7fbba21 against https://github.com/vgstation-coders/vgstation13/blob/006ce38c3d023872c1c9594087ce8348b814184e/maps/tgstation.dmm

Notice the chem dispenser missing and the ChemMaster using the igniter's icon.
The missing icons are not due to layers/planes, as #30 doesn't fix them.

![image](https://user-images.githubusercontent.com/6307265/45539609-8aa43080-b80a-11e8-8a00-b5e2b2857f7a.png)

How it's supposed to look:
![image](https://user-images.githubusercontent.com/6307265/45539814-13bb6780-b80b-11e8-95c6-1363f29d0454.png)

**Comment by SpaceManiac** [comment]
The problem is this parse error:

```
code/modules/power/singularity/singularity.dm, line 40, column 5:
error: got ':', expected one of: '/', '[', contents, newline, '}', identifier
```

The editor should probably report parse errors instead of swallowing them silently.

**Comment by DamianX** [comment]
That seems to be correct, I'll rename this issue.
