### ISSUE TITLE
animate() missing "factor" of "rays" filter

### ISSUE THREAD

**Issue by Kaiochao** [SpaceManiac/SpacemanDMM#323]
https://github.com/SpaceManiac/SpacemanDMM/blob/e979b2e69af0173f1e13d52926ab3dece84f8e1d/crates/dreammaker/src/builtins.rs#L403

**Comment by ZeWaka** [comment]
Fixed in https://github.com/SpaceManiac/SpacemanDMM/pull/154 ?
Seems to be fine locally.
