### ISSUE TITLE
Dreamchecker: Proc reference syntax not recognized as valid

### ISSUE THREAD

**Issue by scrdest** [SpaceManiac/SpacemanDMM#328]
Dreamchecker seems to have a problem recognizing proc refs as legal DM syntax.

For clarity, by proc ref I'm referring to variables whose type is declared to be <root>/proc or <root>/<typepath>/proc, e.g.:
`var/mob/proc/mobmethod = <FOO>` 
`var/turf/grass/summer/proc/grassproc = <FOO>` 
`var/proc/dynamicproc = <FOO>`

This kind of declaration is not only perfectly fine, it is **_required_** to be able to use the builtin `call()` proc on DM procs.

### STEPS TO REPRODUCE:

1. Download SpacemanDMM as of commit [f80d6373e7fcfb809ddc1f88f152dcc1cce67623](https://github.com/SpaceManiac/SpacemanDMM/commit/f80d6373e7fcfb809ddc1f88f152dcc1cce67623) 
2. Build a release version of Dreamchecker (I used Cargo v1.60.0)
3. Check out this repo as of commit [0f3b55db3cc8685ddc5908af603f2ac8017a9f2a](https://github.com/scrdest/DM-GOAI/blob/0f3b55db3cc8685ddc5908af603f2ac8017a9f2a/GOAI/demo/combatant/core.dm#L30)
4. CD into the directory holding the .dme in the project from (3) and run the built dreamchecker.exe
5. The highlighted line in (3) as well as two instances in `demo/_astar.dm` at L80 throw 'error: undefined type: /proc' and 'error: undefined type: /mob/goai/combatant/proc'
6. BONUS STAGE: compile & run the project from (3) against BYOND 514. The fact that the NPC AIs _work at all_ proves this isn't just DM happily NULLing stuff.

**Comment by SpaceManiac** [comment]
> it is **_required_** to be able to use the builtin `call()` proc on DM procs.

How do you figure?

As I understand, DM simply ignores the `proc` keyword in this position, and it has no effect. For instance, `var/mob/proc/foo = new()` infers `/mob` as the type to be new'd.

The most basic correct way to type such variables is to give them no type: `var/foo`. However because such references do in fact have variables you may benefit from an interface type like this to expose them: https://codedocs.tgstation13.org/procpath.html

**Comment by scrdest** [comment]
Thanks for the prompt response!

Hmm, I'm a bit confused - I distinctly remember _some_ cases where the compiler screamed at me until I added /proc to the path for this usecase in the Urist SS13 codebase, but I couldn't reproduce it in my project. 

I'll provisionally close this for now and reopen if I can get a solid example. Sorry for the hassle.
