### ISSUE TITLE
Enclosing comments ignored by VSCode extension

### ISSUE THREAD

**Issue by Kenionatus** [SpaceManiac/SpacemanDMM#332]
According to the DMdoc readme:

> //! Enclosing comments follow their item.

However, when using this style, the VSCode extension does not display the comment in the mouse over menu for the respective datum. Language server was reloaded and project was rebuilt, both with the same result.

When mousing over variable with enclosed comment, it does not display the comment.
![image](https://user-images.githubusercontent.com/54814353/180650668-b5d41a70-7d21-4fcf-9da8-74e21815c591.png)
When mousing over variable with comment on previous line, the comment is displayed.
![image](https://user-images.githubusercontent.com/54814353/180650693-3d22354b-9e4b-4c76-b587-a1b42cc0ca21.png)

**Comment by checkraisefold** [comment]
make an issue on spacemandmm github..?

**Comment by Andrew-Fall** [comment]
Can verify this is still an issue and is inter-user/system.

**Comment by MeggalBozale** [comment]
Can verify this is still an issue.
