### ISSUE TITLE
Resizing the window does not work on macOS

### ISSUE THREAD

**Issue by PJB3005** [SpaceManiac/SpacemanDMM#34]
![image](https://user-images.githubusercontent.com/8107459/45771235-e45e8d80-bc44-11e8-8184-cc2061048d21.png)

The GUI seems to behave as if the window did correctly resize though.

**Comment by SpaceManiac** [comment]
Cannot reproduce on either Linux or Windows. Unfortunately, I do not have a macOS machine to test against.

**Comment by SpaceManiac** [comment]
Fixed by #51.
