### ISSUE TITLE
515 compatibility

### ISSUE THREAD

**Issue by Mothblocks** [SpaceManiac/SpacemanDMM#341]
- `call_ext` now exists to replace `call`, with similar syntax
- `type::variable_name` now exists in static definitions, to alleviate a breaking change to NAMEOF

http://www.byond.com/forum/post/2828780

**Comment by SpaceManiac** [comment]
Release notes with non-explicitly-breaking features: http://www.byond.com/docs/notes/515.html

Will likely only get to this after 515 has stewed in beta for a bit and codebases like /tg/ are actually looking to start using it.

**Comment by Mothblocks** [comment]
oh yeah pointers are a thing now too lol

**Comment by Mothblocks** [comment]
515 also adds `__TYPE__` and `__PROC__`.

**Comment by Spookerton** [comment]
also adds the /final/ var sugar.
<https://www.byond.com/docs/ref/#/var/final>

**Comment by Mothblocks** [comment]
Also adds `/proc/bla() as type`, which is equivalent to `RETURN_TYPE` in SDMM.

**Comment by Mothblocks** [comment]
> Will likely only get to this after 515 has stewed in beta for a bit and codebases like /tg/ are actually looking to start using it.

@SpaceManiac  It's been about 6 months and we're about to require 515 for building.

The two biggest failures right now are no `nameof` and no `savefile/byond_version`.

**Comment by Mothblocks** [comment]
So we need:

- call_ext
- nameof
- refcount
- savefile/byond_version
- `::` syntax
- `:` syntax

Those last two are important because I can't just define over those

**Comment by Mothblocks** [comment]
I'm wrong about `:`, it was SDMM incorrectly reporting `::` and I got confused

**Comment by Zandario** [comment]
> also adds the `/final/` var sugar. [byond.com/docs/ref/#/var/final](https://www.byond.com/docs/ref/#/var/final)

`/final/` is also used for procs, it should probably be reserved to prevent people for accidentally finding out the hard way

e.g.
![image](https://user-images.githubusercontent.com/34761877/234427347-3196637f-8105-4fbb-b9b8-201332de0755.png)

**Comment by Spookerton** [comment]
Recent attack mitigation stuff in late 515 won't be backported to stable. Much of this can be hidden with a version file at the moment, but the :: accessor and & pointer syntax are unavoidable.

**Comment by Spookerton** [comment]
https://github.com/SpaceManiac/SpacemanDMM/pull/353 handled call_ext
240d8e02c41e7f8f3f7479354e0dcca362ec511e handled :: scope token
41297597fb29a565375106189309426b8ef2c3a9 handled /final/ sugar
32bf1b3b98c3e81e576300ec32bfe357813e4bae handled & and * pointer stuff

https://github.com/SpaceManiac/SpacemanDMM/pull/354 does simple constants and proc signatures, op lists remaining things afaik having gone through the ref for byondver=515 hits

**Comment by LemonInTheDark** [comment]
@SpaceManiac are we free or is there more to do

**Comment by SpaceManiac** [comment]
/tg/station now passes dreamchecker in 515 mode. Sure to be bugs or something missed along the way but I think that's the majority of it.

**Comment by LemonInTheDark** [comment]
aight ws, sounds great

**Comment by SpaceManiac** [comment]
Closing this since 515 support was released in [suite 1.8](https://github.com/SpaceManiac/SpacemanDMM/releases/tag/suite-1.8). Any bugs should now be their own tickets, example:
- #374
- #375
