### ISSUE TITLE
Can't Ctrl+Click filepaths in VSC terminal

### ISSUE THREAD

**Issue by Shadow-Quill** [SpaceManiac/SpacemanDMM#343]
Error/warning prefixes don't have a space between the filename/line and the actual `error:`
eg:
`code\controllers\subsystems\timer.dm:508:error: stack_trace: undefined proc`

Which means Ctrl+Clicking on the filename makes VSC attempt to take you to `[...].dm:508:error:`.

**Comment by AnturK** [comment]
The terminal links are handled by vscode itself (https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/terminal/browser/links/terminalLocalLinkDetector.ts) and can't be managed by extensions/langserver so this is byond issue.
