### ISSUE TITLE
SpacemanDMM requires a OS downgrade to use 

### ISSUE THREAD

**Issue by bawbbawbins** [SpaceManiac/SpacemanDMM#365]
I don't see why I should have to downgrade from 7 to 10 to use this.

It should be easy enough to port to 7

**Comment by SpaceManiac** [comment]
What's broken?

**Comment by SpaceManiac** [comment]
Microsoft's extended support for Windows Server 2012 R2, the last supported Windows version older than 10, [ends in three days](https://learn.microsoft.com/en-us/lifecycle/announcements/windows-server-2012-r2-end-of-support). Rust itself will be [dropping support for Windows <10 in February 2024](https://github.com/rust-lang/compiler-team/issues/651). If you need a legacy version of SpacemanDMM, you should compile it yourself. If you can identify the actual problem and submit a reasonable PR to fix it, I may accept it.
