### ISSUE TITLE
Union return types don't parse correctly

### ISSUE THREAD

**Issue by ZeWaka** [SpaceManiac/SpacemanDMM#385]
Error:
```
got '|', expected one of: '{', ';', if, while, do, for, spawn, switch, try, set, break, continue, del, var, return, CRASH, throw, goto, operator, term
```

Code: 
```ts
/datum/hud/critter/proc/create_stamina_element() as num | null
```

**Comment by ike709** [comment]
I can't be bothered to find the BYOND bug report, but note that this was broken in BYOND too until very recently.

**Comment by SpaceManiac** [comment]
`/datum/hud | null` isn't legal in BYOND either so I'll assume you mean input types like `num|text` which do need fixing
