### ISSUE TITLE
Outline tree doesn't associate a variable with a class if multiple are present, or if just one is present

### ISSUE THREAD

**Issue by Zandario** [SpaceManiac/SpacemanDMM#394]
If a class definition has more than one variable inside of it, when it creates a dropdown for the class, it fails to contain the first variable and leaves it in the global scope for the file.

It also seems to fail to make a scope with only one variable present, so you get an isolated class and variable in the outline.

![image](https://github.com/SpaceManiac/SpacemanDMM/assets/34761877/a59de54c-b95d-4587-a999-161dc0487009)

<details><summary>This can be very confusing if you use alphabetical (like a heathen)</summary>
<p>

![image](https://github.com/SpaceManiac/SpacemanDMM/assets/34761877/2e82a0d3-737f-4e6a-a3d2-d79fc54c2765)

</p>
</details> 

<details><summary>Example code used</summary>

```dm
/foo
	var/foo_name

/foo/bar
	var/bar_name
	var/bar_desc
	var/bar_another_var

/foo/bar/baz
	foo_name = TRUE
	bar_desc = FALSE

```

</details>

**Comment by Zandario** [comment]
Do note that these issues do not impact procs or verbs

**Comment by SpaceManiac** [comment]
It's still possible for an empty proc at the end of a tree block to escape it in the outline. Might look at that later or might ignore it until someone else complains.
