### ISSUE TITLE
return type `as list` and is being labeled as a bad return type

### ISSUE THREAD

**Issue by Zandario** [SpaceManiac/SpacemanDMM#399]
This is something that is in the ref and works fine.
https://www.byond.com/docs/ref/#/proc
```dm
proc/return_list() as list
	return list()
```
![image](https://github.com/SpaceManiac/SpacemanDMM/assets/34761877/b22eb879-f176-495e-b8d3-d056c16e275a)

**Comment by ZeWaka** [comment]
so uhh this is Wonky
![image](https://github.com/user-attachments/assets/073e8a7e-93be-4413-966e-5b94259d6b0e)

**Comment by Zandario** [comment]
`as list` is a special one for proc returns, consider it's normally `in list()`

**Comment by SpaceManiac** [comment]
Looks like `as list` is offhandedly mentioned in the docs, but it's definitely weird because it's not a valid in an `as()` expression, so I don't know what numeric `InputType` value to assign it, yet somehow `/proc/foo() as obj | list | mob` is valid DM.

**Comment by SpaceManiac** [comment]
`as(movable)` and `as(atom)` seem undocumented, but work sanely, so they're in.

**Comment by SpaceManiac** [comment]
I'd like to know what `list`'s real value is to avoid collisions or other future oddities, but I've given it a placeholder value for now and made it act like any other input type as far as SpacemanDMM is concerned, so `as list` will parse.
