### ISSUE TITLE
fexists() does not always work correctly

### ISSUE THREAD

**Issue by TheTyrant25** [SpaceManiac/SpacemanDMM#400]
In goonstation's dme file:
```dm
#if fexists("./+secret/__secret.dme")
#include ".\+secret\__secret.dme" // line 34
#endif
```
This code is for handling the secret submodule of goonstation.
The DM language client throws the following warning:
```
duplicate #include "filepath/__secret.dme" dm-langserver(duplicate_include) [Ln 34, Col 1]
filepath\goonstation.dme[Ln 31, Col 1]: previously included here
```
(Where `filepath` is the cloned repository's filepath.)

`__secret.dme` was previously `#include`d on line 31 but not correctly detected by `#if fexists()` on line 33.

Multiple users have reported this error, and a workaround is being made to get around this. That said, it should ideally just work correctly and detect `__secret.dme` already having been included earlier.

Possibly the `fexist()` check is broken, or the langserver is reading the .dme file incorrectly.

**Comment by SpaceManiac** [comment]
> not correctly detected by `#if fexists()`

How do you figure? The file exists, so the `#if` passes, and the file is included a second time, per the code.

**Comment by ZeWaka** [comment]
this issue is invalid yes

**Comment by TheTyrant25** [comment]
the problem was more complex than originally thought my bad
