### ISSUE TITLE
`bad input type: 'movable'`

### ISSUE THREAD

**Issue by ZeWaka** [SpaceManiac/SpacemanDMM#404]
This compiles in BYOND (and works as expected ingame).

not documented on https://www.byond.com/docs/ref/#/verb/arguments though lol

**Comment by ZeWaka** [comment]
This is also the case for `atom`

**Comment by SpaceManiac** [comment]
This was fixed on master recently (see #399). I've just pushed an update that the VSC extension will pick up.
