### ISSUE TITLE
Preprocessor can't parse #if with potentially undefined macro

### ISSUE THREAD

**Issue by DamianX** [SpaceManiac/SpacemanDMM#64]
```
#ifdef A
	#if A == 0
	#endif
#endif
```

This works in DM because `#if A == 0` is only evaluated if `A` is defined, but SpacemanDMM tries to parse it no matter what.

Possibly relevant commit: https://github.com/SpaceManiac/SpacemanDMM/commit/4f372d6f87e666e608ec41e4e881305815846e84

**Comment by SpaceManiac** [comment]
The original intent of that commit was that stuff like this would still generate warnings (mostly because the fake directive could have meant to be an elif/endif):
```dm
#if 0
#fakedirective
#endif
```

But it should clearly not be actually evaluating the RHS of `if`s. Good catch.
