### ISSUE TITLE
Can't parse ()

### ISSUE THREAD

**Issue by DamianX** [SpaceManiac/SpacemanDMM#67]
```
world/New()
	return (0 ? 1 : ())
```

> line 2, column 19:
error: got ')', expected one of: operator, term

Apparently that's valid DM and it does nothing. Actually found in the wild [here](https://github.com/vgstation-coders/vgstation13/blob/69d3ccc82621dc012927df7cfde31ba295111da3/code/game/machinery/newscaster.dm#L266).

**Comment by SpaceManiac** [comment]
Weird construct. Debating WONTFIXing it.

Works and evaluates to `null`:

* `src << (prob(50) ? 1 : ())`
* `src << (prob(50) ? () : 1)`
* `src << "[()]"`
* `src << softcodeproc(())`

`error: missing expression`:

* `src << ()`
* `src << isnull(())`
* `src << (1 + ())`
* `src << (() ? 1 : 2)`

**Comment by DamianX** [comment]
We can just replace occurrences with `null`, I think WONTFIXing it is totally fine.
