### ISSUE TITLE
VSCode langserver bluescreens Windows 10 18875.1000

### ISSUE THREAD

**Issue by AffectedArc07** [SpaceManiac/SpacemanDMM#74]
After updating Windows to 18875.1000, upon starting the langserver, my PC would immediately bluescreen for either `PAGE_FAULT_IN_NONPAGED_AREA` or `KERNEL_SECURITY_CHECK_FAILURE`. 

After disabling the langserver extension, I could edit files.

I have no idea what causes this, but it happens anyway
![image](https://user-images.githubusercontent.com/25063394/56090213-1c564800-5e97-11e9-9454-ef030db748a3.png)

I blame the windows 10 beta

**Comment by SpaceManiac** [comment]
Probably beyond my power to fix

**Comment by AffectedArc07** [comment]
Stopped happening after moving my mouse to a different USB port


Windows everyone
