### ISSUE TITLE
Suggestion: Task integration for running the resulting DMB

### ISSUE THREAD

**Issue by TheGoddessInari** [SpaceManiac/SpacemanDMM#75]
It'd be nice if we could then run the resulting build directly from VS code (invoking dreamseeker on the DMB, I assume) as part of the language integration.

**Comment by ZeWaka** [comment]
`dreamdaemon.exe enviroment.dme -trusted`

can replace `daemon` with `seeker` as separate option

https://github.com/SpaceManiac/vscode-dm-langclient/blob/65d31ed3b4537d8af64bd50e6c32acecd67f6aee/src/tasks.ts#L40-L47

See .py reference:
https://github.com/Wirewraith/sublime-byond/blob/73e5f5683c1fd48136cbb5c71ca4fa69f6fc28ab/byond_build.py#L58

**Comment by SpaceManiac** [comment]
My main concerns are:

- dreamdaemon doesn't exit on server shutdown
- neither dreamdaemon nor dreamseeker provides logs
- dreamseeker is unavailable on Linux (Wine workaround?)

**Comment by SpaceManiac** [comment]
Available on master if you want to try it out, will hit release at some point.

**Comment by SpaceManiac** [comment]
vscode v0.1.4 out
