### ISSUE TITLE
"else" gets autocompleted to "SHUTTLE_SOMEONE_ELSE_DOCKED"

### ISSUE THREAD

**Issue by actioninja** [SpaceManiac/SpacemanDMM#76]
Fairly self explanatory, `else` keyword is getting autocompleted when it shouldn't be. If you type `else` and then immediately hit enter, it takes the autocomplete result from the first recommend which happens to normally be `SHUTTLE_SOMEONE_ELSE_DOCKED`

This can be averted by adding a space after the else, but it still is a quality of life thing that would be nice to have fixed.

**Comment by SpaceManiac** [comment]
Yeah, autocomplete should probably include keywords
