### ISSUE TITLE
Can't parse empty for loop

### ISSUE THREAD

**Issue by DamianX** [SpaceManiac/SpacemanDMM#80]
```
/proc/a()
    for()
        world.log << 1
```

```
error: for-in-list must start with variable
```

Arguably should be replaced with something like `while(TRUE)` but I don't know if you want to be able to parse this anyway.

**Comment by SpaceManiac** [comment]
Downgrading this to a "nice-to-have" given that `while(TRUE)` is functionally equivalent and less of a quagmire for me to deal with.
