### ISSUE TITLE
definition counting is not respecting #IF directives

### ISSUE THREAD

**Issue by ZeWaka** [SpaceManiac/SpacemanDMM#87]
This will error with a redefinition error of `bop1` and `bop2`:

This can be used to have variable debug logging, based on a changeable verbosity number.
```c
#define bop1(msg)
#define bop2(msg)

#ifdef DEBUG
#define CHANGEABLE 2

#define bop_base(change, msg) world << "[change], [msg]"

#if CHANGEABLE >= 1
	#define bop1(beep) bop_base( "less", msg )
#endif

#if CHANGEABLE >= 2
	#define bop2(msg) CDBG( "more", msg )
#endif

#endif
```

**Comment by SpaceManiac** [comment]
This is what I would expect the output to be if `DEBUG` is in fact defined.

Perhaps you want to `#undef bop1` immediately before redefining it?

**Comment by ZeWaka** [comment]
Yeah, that works. Fair enough!
