### ISSUE TITLE
Make h2 headings have an anchor link

### ISSUE THREAD

**Issue by optimumtact** [SpaceManiac/SpacemanDMM#91]
You can insert into the markup an h2 header with
` ## your header`

It would be cool if in the final output that header had a little anchor link so you can deep link people to the section indicated by that header

example icon:
https://www.pinclipart.com/pindetail/moxio_link-chain-url-uri-anchor-svg-png-icon/

**Comment by optimumtact** [comment]
actually the same would be good for h3 anchors too

**Comment by SpaceManiac** [comment]
The clickable icon would be kind of a pain for reasons but heading tags now have `id` attributes to make them deep-linkable.
