### ISSUE TITLE
Auto link to defines and procs

### ISSUE THREAD

**Issue by optimumtact** [SpaceManiac/SpacemanDMM#92]
Having a shorthand syntax like
`[text](#def:<nameofdev>)`
auto gen a link to the define or proc would definitely be useful, to save having to type out the relative links (including the anchor)

should help keep the comments from ballooning in size

**Comment by SpaceManiac** [comment]
`[text][/path/to/thing]` is the currently supported syntax, though its implementation leaves a bit to be desired.

**Comment by SpaceManiac** [comment]
The following references will now be resolved:

- `[DEFINE_NAME]`
- `[/mob]`
- `[/mob/proc/Dizzy]`
- `[/mob/var/stat]`

e.g. `[DEFINE_NAME]` for a shorthand link or `[some define][DEFINE_NAME]` to customize link text.

**Comment by optimumtact** [comment]
awesome!
