### ISSUE TITLE
"malformed defined() call" errors for defined([anything defined])

### ISSUE THREAD

**Issue by Kaiochao** [SpaceManiac/SpacemanDMM#96]
```dm
#define FOO

#if defined(FOO)
// error
#endif

#if !defined(FOO)
// error
#endif

#ifdef FOO
// no error
#endif

#ifndef FOO
// no error
#endif
```

**Comment by ZeWaka** [comment]
I encountered this on the Goonstation codebase. I ended up just changing all of the syntax, to achieve consistency across the code.

**Comment by Kaiochao** [comment]
`defined()` exists so that it can be logic-chained like so:
```dm
#if defined(C) || defined(A) && !defined(B)
```

**Comment by SpaceManiac** [comment]
Used to work, I must have broken it at some point

**Comment by spookydonut** [comment]
@SpaceManiac I believe it was 0a650be853b005ab4a333c97ff5e9372fccd237c that broke it.
