### ISSUE TITLE
Duplicate #includes should not give a warning

### ISSUE THREAD

**Issue by Kaiochao** [SpaceManiac/SpacemanDMM#97]

**Comment by ZeWaka** [comment]
I would argue that it should. What's a possible usecase of this being beneficial?

**Comment by Kaiochao** [comment]
Any file that depends on another file should be allowed to #include that file at the top of its own file. DM already prevents duplicate includes.

**Comment by SpaceManiac** [comment]
Leaving open because I don't have a separate ticket for it, but ideally will someday be covered by an ability to configure warnings
